os:
  - linux
dist: trusty

addons:
  rethinkdb: '2.3.4'

language: c

install:
  - |
      git clone --depth=1 -b devel https://github.com/nim-lang/Nim.git
      cd Nim
      git clone --depth 1 https://github.com/nim-lang/csources.git
      cd csources
      sh build.sh
      cd ../
      bin/nim c koch
      ./koch boot -d:release
      ./koch nimble
      cd ../

addons:
  rethinkdb: "2.3.5"

before_script:
  - export PATH="`pwd`/Nim/bin:$PATH"
  - nimble install -d -y

script:
    - nimble test
